### ISSUE TITLE
 rabbitmq或者 rocketmq 能支持日志吗

### ISSUE THREAD

**Issue by gkuanine** [tx7do/kratos-transport#1]
rabbitmq或者 rocketmq 能支持日志吗

**Comment by tx7do** [comment]
> rabbitmq或者 rocketmq 能支持日志吗

哪方面的日志呀？然后，日志输出到哪里去？

**Comment by gkuanine** [comment]
tracing 日志追踪

**Comment by tx7do** [comment]
> tracing 日志追踪

这个我也想支持，当时没有看到相关的实现，最近没空去看这一块，MQ能够追踪那是自然好的。

**Comment by ckall** [comment]
大佬可以支持rocketmq吗?

**Comment by tx7do** [comment]
> 

已经支持rocketmq
