### ISSUE TITLE
utils 重命名为 keepalive 后，需要给 transport 升一下 tag

### ISSUE THREAD

**Issue by xray-bit** [tx7do/kratos-transport#107]
如果升级 `github.com/tx7do/kratos-transport`，`github.com/tx7do/kratos-transport/transport/***` 会提示找不到 utils 包

**Comment by tx7do** [comment]
呃？不是吧。。。。

**Comment by tx7do** [comment]
这个可能是go get all的一个bug。
碰到这种情况，你就需要手动去升级卡住的依赖库。只要把卡住的依赖库升级上去，你就可以了再使用go get all升级整个的依赖库。 。

**Comment by xray-bit** [comment]
好的，谢谢！
