### ISSUE TITLE
注册Asynq服务到nacos报错

### ISSUE THREAD

**Issue by lugcz** [tx7do/kratos-transport#111]
``报错内容：panic: RegisterInstance err retry3times request failed,err=request return error code 400,tcp://:55454

new App代码：
`func newApp(ll log.Logger, rr registry.Registrar, gs *grpc.Server, hs *http.Server, ws *websocket.Server,as *asynq.Server) *kratos.App {
	return bootstrap.NewApp(ll, rr, gs, hs, ws, as)
}`

**Comment by tx7do** [comment]
保活同时只能存在一个，否则就会出这个错误的。你有grpc，http任意一个，就可以把mq的保活给关闭掉了。也就是说，websocket和asynq的保活都可以关闭掉了。

104658卢广出 ***@***.***> 于2024年11月27日周三 16:57写道：

**Comment by tx7do** [comment]
我之所以加了保活，是因为有时候会存在某一个服务只有一个MQ，那么，注册服务便无法感知到该服务的死活。这个时候，我们就需要一个保活服务。

**Comment by lugcz** [comment]
websocket 需要增加keepalive option

**Comment by lugcz** [comment]
asynq 配置了：asynq.WithEnableKeepAlive(false),
`// NewAsynqServer create a asynq server.
func NewAsynqServer(conf *conf.Bootstrap, _ log.Logger, svc *service.RoomService) *asynq.Server {
	srv := asynq.NewServer(
		asynq.WithAddress(conf.Server.Asynq.Endpoint),
		asynq.WithRedisPassword(conf.Server.Asynq.Password),
		asynq.WithRedisDatabase(int(conf.Server.Asynq.Db)),
		asynq.WithLocation("Asia/Shanghai"),
		asynq.WithEnableKeepAlive(false),
	)` 问题还存在

**Comment by lugcz** [comment]
我在app/server新建一个main.go，把asynq单独注册一个服务了

**Comment by lugcz** [comment]
websocket 能正常注册的，asynq获取不到endpoint导致无法注册呢

**Comment by lugcz** [comment]
看了keepalive generateEndpoint 方法源码 这个KRATOS_TRANSPORT_KEEPALIVE_INTERFACE环境变量没设置：export KRATOS_TRANSPORT_KEEPALIVE_INTERFACE=ens33, 已经能成功启动啦  谢谢您的回复 ^_^
