### ISSUE TITLE
kratos版本不一致 tr.reqHeader 报错

### ISSUE THREAD

**Issue by shaohongwu** [tx7do/kratos-transport#45]
github.com/go-kratos/kratos/v2 v2.6.2
github.com/tx7do/kratos-transport v1.0.5

kratos-transport 用kafka 有个报错
 cannot use tr.reqHeader (variable of type headerCarrier) as transport.Header value in return statement: headerCarrier does not implement transport.Header (missing method Add)

**Comment by farums** [comment]
супер
