### ISSUE TITLE
go mod tidy的默认版本参数类型不对

### ISSUE THREAD

**Issue by mpraiser** [tx7do/kratos-transport#46]
使用go mod tidy时，默认的github.com/tx7d0/kratos-transport/transport/kafka版本是v1.0.2
此版本kafka.WithCodec()接受参数类型为encoding.Codec，而不是string，而[kratos-cqrs的范例代码](https://github.com/tx7do/kratos-cqrs/blob/main/app/logger/job/internal/server/kafka.go)中传入string，会报错。

手动在go.mod里指定版本为v0.0.0-20221220110912-9db1b79d385c可以解决这个问题。请问能否让go mod tidy自动指定的版本为正确的版本？

**Comment by tx7do** [comment]
> 使用go mod tidy时，默认的github.com/tx7d0/kratos-transport/transport/kafka版本是v1.0.2 此版本kafka.WithCodec()接受参数类型为encoding.Codec，而不是string，而[kratos-cqrs的范例代码](https://github.com/tx7do/kratos-cqrs/blob/main/app/logger/job/internal/server/kafka.go)中传入string，会报错。
> 
> 手动在go.mod里指定版本为v0.0.0-20221220110912-9db1b79d385c可以解决这个问题。请问能否让go mod tidy自动指定的版本为正确的版本？

因为最近做了一些升级，可能示例就没有升级过来了，有空我就升级一下。
