### ISSUE TITLE
如何根据userId的hash值将数据发送到指定的分区呢

### ISSUE THREAD

**Issue by Wanghongw** [tx7do/kratos-transport#47]
看了下broker/kafka中的代码，调用实际上里面封装了segmentio/kafka-go这个包的方法，但是在WriteMessages方法中并没有根据传来字段的hash值指定分区，是现在的版本还不支持吗？

**Comment by Wanghongw** [comment]
我试了下，在调用Publish方法的时候，指定了一个配置：kafka.WithBalancer(kafka.BalancerReferenceHash)，但是实际测试了下，消息还是没办法发送到指定分区，我的代码如下：
```go
package main

import (
	"context"
	"fmt"
	"github.com/tx7do/kratos-transport/broker"
	"github.com/tx7do/kratos-transport/broker/kafka"
	"time"
)

const (
	// TODO 最好做成配置项！
	topic             = "my-topic"
	numPartitions     = 6
	wrongPartitionNum = 0 // Notice 没有传userId统统往 分区0 中发送，这种做法有点极端～最好加一个随机的数(保证加完的值不超过分区大小)
)

func main() {

	userIds := []string{"user1", "user2", "user3", "user4", "user1", "user1", "user1"}
	fmt.Println("userIds: ", userIds)

	// 创建 Kafka 生产者
	ctx := context.Background()
	producer := kafka.NewBroker(
		broker.WithOptionContext(ctx),
		broker.WithAddress([]string{"localhost:9092"}...),
		broker.WithCodec("json"),
		//发送批次大小
		kafka.WithBatchSize(1),
		// 异步发送消息
		kafka.WithAsync(true),
	)

	err := producer.Init()
	if err != nil {
		panic(err)
	}
	err = producer.Connect()
	if err != nil {
		panic(err)
	}

	//fmt.Println("producer: ", producer)

	// 发送消息
	// TODO 后面改成并发的～～～
	for _, userId := range userIds {
		currStr := fmt.Sprintf("hello-%v", userId)
		msg := &broker.Message{
			Headers: broker.Headers{
				"userId": userId,
			},
			Body: currStr,
		}
		err = producer.Publish(
			topic,
			msg,
			// Notice 负载均衡器～～～
			kafka.WithBalancer(kafka.BalancerReferenceHash),
		)
		fmt.Println("err: ", err)
		if err != nil {
			panic(err)
		}
	}

	// Notice 防止消息没发完 主协程停了 消息发不出去
	time.Sleep(time.Second * 2)

	producer.Disconnect()
}


```

**Comment by Wanghongw** [comment]
好的 非常感谢你的反馈 项目中有这样的需求场景，我先用segmentio/kafka-go这个包来做，期待后面加上指定分区的功能

**Comment by tx7do** [comment]
我刚刚看了kafka-go的 [Issue905](https://github.com/segmentio/kafka-go/issues/905)，并不是简单的把平衡器设置为`kafka.BalancerReferenceHash`就可以了，还得新建`ReferenceHashPartitioner`。

**Comment by tx7do** [comment]
配置接口做了一些调整：
1. 去除了kafka.WithBalancer；
2. 新增了：WithLeastBytesBalancer、WithRoundRobinBalancer、WithHashBalancer、WithReferenceHashBalancer、WithCrc32Balancer、WithMurmur2Balancer。

你可以试一试看。

**Comment by Wanghongw** [comment]
> 

OK 今天有时间我写个demo试试

**Comment by Wanghongw** [comment]
@tx7do  我还遇到一个版本问题，就是我使用go get获取kratos-transport最新的1.0.6版本的代码，但是broker目录中没有kafka这被目录：
![image](https://github.com/tx7do/kratos-transport/assets/37063373/35660f3b-449e-43f3-bd83-f790a1433fac)

但是我clone下来的源码是有的：
![image](https://github.com/tx7do/kratos-transport/assets/37063373/ce580ea4-cb9f-4a18-89ee-3aee26f89fcc)

**Comment by tx7do** [comment]
这个没问题的。因为都拆分开了，kafka不在这里。

Wanghongw ***@***.***> 于2023年6月21日周三 17:55写道：

**Comment by Wanghongw** [comment]
@tx7do  我试着写了一个demo，发现有问题，我想指定的userIds中相同userId的将消息发送到同一个分区，但是测试的结果不是这样的，我的代码如下：
```go
package main

import (
	"context"
	"fmt"
	"github.com/tx7do/kratos-transport/broker"
	"github.com/tx7do/kratos-transport/broker/kafka"
	"hash"
	"hash/fnv"
	"time"
)

const (
	// TODO 最好做成配置项！
	topic         = "my-topic"
	numPartitions = 6
)

func main() {

	userIds := []string{"user1", "user1", "user1", "user1", "user2", "user3", "user4"}
	fmt.Println("userIds: ", userIds)

	// 创建 Kafka 生产者
	ctx := context.Background()
	producer := kafka.NewBroker(
		broker.WithOptionContext(ctx),
		broker.WithAddress([]string{"localhost:9092"}...),
		broker.WithCodec("json"),
		//发送批次大小
		kafka.WithBatchSize(1),
		// 异步发送消息
		kafka.WithAsync(true),
	)

	err := producer.Init()
	if err != nil {
		panic(err)
	}
	err = producer.Connect()
	if err != nil {
		panic(err)
	}

	//fmt.Println("producer: ", producer)

	// 发送消息
	for idx, userId := range userIds {
		currStr := fmt.Sprintf("hello-%v-%v", idx, userId)
		msg := &broker.Message{
			Headers: broker.Headers{
				"userId": userId,
			},
			Body: currStr,
		}
		err = producer.Publish(
			topic,
			msg,
			// Notice 负载均衡器～根据用户id的hash指定分区发送消息
			kafka.WithHashBalancer(hashFunc(userId)),
		)
		fmt.Println("err: ", err)
		if err != nil {
			panic(err)
		}
	}

	// Notice 防止消息没发完 主协程停了 消息发不出去
	time.Sleep(time.Second * 2)

	producer.Disconnect()
}

func hashFunc(s string) hash.Hash32 {
	h := fnv.New32a()
	h.Write([]byte(s))
	return h
}
```
结果0、1、2、3这几个分区都有user1这个数据：
<img width="582" alt="image" src="https://github.com/tx7do/kratos-transport/assets/37063373/b1bdaa42-fa27-4eab-a89c-db69e04b6b19">
<img width="560" alt="image" src="https://github.com/tx7do/kratos-transport/assets/37063373/c2ab17f3-7c93-4668-9d91-a6ed9b9228d2">
<img width="559" alt="image" src="https://github.com/tx7do/kratos-transport/assets/37063373/9cf7b25b-8b66-40ab-aa50-a31fd275539f">
<img width="559" alt="image" src="https://github.com/tx7do/kratos-transport/assets/37063373/cc28f4c1-3816-4727-99d0-040024eb0281">

**Comment by tx7do** [comment]
ok哒。

**Comment by Vericlongmore** [comment]
kafka.NewBroker 怎么设置sasl和PlainMechanism ，怎么设置用户名密码

**Comment by tx7do** [comment]
请看：
- kratos-transport <https://github.com/tx7do/kratos-transport/tree/main>
- /broker <https://github.com/tx7do/kratos-transport/tree/main/broker>
- /kafka <https://github.com/tx7do/kratos-transport/tree/main/broker/kafka>
/options.go



// WithPlainMechanism PLAIN认证信息
func WithPlainMechanism(username, password string) broker.Option {
mechanism := plain.Mechanism{
Username: username,
Password: password,
}
return broker.OptionContextWithValue(mechanismKey{}, mechanism)
}

// WithScramMechanism SCRAM认证信息
func WithScramMechanism(algoName ScramAlgorithm, username, password string)
broker.Option {
var algo scram.Algorithm
switch algoName {
case ScramAlgorithmSHA256:
algo = scram.SHA256
case ScramAlgorithmSHA512:
algo = scram.SHA512
}

mechanism, err := scram.Mechanism(algo, username, password)
if err != nil {
panic(err)
}

return broker.OptionContextWithValue(mechanismKey{}, mechanism)
}

Vericlongmore ***@***.***> 于2024年6月18日周二 18:13写道：
