### ISSUE TITLE
mqtt断线无法重连

### ISSUE THREAD

**Issue by leyou240** [tx7do/kratos-transport#5]
如题

**Comment by tx7do** [comment]
> 

不能吧，我之前测试过的。

**Comment by leyou240** [comment]
我也是测试后发现的问题，我用nats启动的mqtt服务。
我用依赖库github.com/eclipse/paho.mqtt.golang，直接使用也可以重连。

**Comment by tx7do** [comment]
我今天大更新了一下，之前一直没把codec整合进去，今天整合进去了，算是完整了。
明天，我测试下mqtt的这个问题。
我一直都是用的rabbitmq的mqtt插件和emqx做的测试，当时好像是没问题的样子。

**Comment by tx7do** [comment]
我忽然想起来，NATS的我之前试过，好像它实现得不太完全。是有问题的。
