### ISSUE TITLE
考虑支持RocketMQ5.x

### ISSUE THREAD

**Issue by shanezhiu** [tx7do/kratos-transport#51]
目前sdk仅支持RocketMQ4.x, 还没法支持RocketMQ5.x

**Comment by tx7do** [comment]
巧妇难为无米之炊，那也得他们推出来sdk才好，没有sdk，我也是无能为力的。这个X的RocketMQ，特麻烦，捐给别人的东西一套，自己又一套，老烦人了。

**Comment by shanezhiu** [comment]
> 巧妇难为无米之炊，那也得他们推出来sdk才好，没有sdk，我也是无能为力的。这个X的RocketMQ，特麻烦，捐给别人的东西一套，自己又一套，老烦人了。
实话说，我刚开始也是一脸懵逼，而且文档里没有特别说明sdk情况，只能自己找上下文

**Comment by shanezhiu** [comment]
> 巧妇难为无米之炊，那也得他们推出来sdk才好，没有sdk，我也是无能为力的。这个X的RocketMQ，特麻烦，捐给别人的东西一套，自己又一套，老烦人了。

现在已经有了，可以考虑缝合下 https://github.com/apache/rocketmq-clients/tree/master/golang

**Comment by shanezhiu** [comment]
> github.com/aliyunmq/mq-http-go-sdk github.com/apache/rocketmq-client-go/v2 github.com/apache/rocketmq-clients/golang
> 
> 特么的，一个MQ，整这么多SDK，只有一个无言……

我去质问他们

**Comment by tx7do** [comment]
已经同时支持了3个驱动。
