### ISSUE TITLE
kafka是否可以支持像NSQ那样WithDeferredPublish的配置，实现延迟队列呢？

### ISSUE THREAD

**Issue by Wanghongw** [tx7do/kratos-transport#53]
kafka是否可以支持像NSQ那样WithDeferredPublish的配置，实现延迟队列呢？

**Comment by tx7do** [comment]
只要Kafka支持，就没问题，若是不支持，那我也是没有办法的。

若是需要延迟的功能，你还有别的选择：asynq和machinery。
