### ISSUE TITLE
rabbitmq存在方法未实现

### ISSUE THREAD

**Issue by zhongy-web** [tx7do/kratos-transport#54]
![image](https://github.com/tx7do/kratos-transport/assets/70579263/3a067ff5-b4de-4cc5-b450-7018718b1364)
![image](https://github.com/tx7do/kratos-transport/assets/70579263/4d067b3f-c80b-4457-ae6e-615ea70a50fd)

**Comment by tx7do** [comment]
更新到最新版本就可以了。之前没注意，升级了kratos的版本，结果出现了这个问题。我都已经修复了。更新就是了。

zhongy-web ***@***.***> 于2023年7月28日周五 14:29写道：

**Comment by zhongy-web** [comment]
要怎么才能让依赖变成这样？
<img width="658" alt="image" src="https://github.com/tx7do/kratos-transport/assets/70579263/4bd75187-4383-4a72-87e9-8e97130df680">
我这里好像只能获取这个版本的依赖
![image](https://github.com/tx7do/kratos-transport/assets/70579263/27ef7a87-0082-4f9b-8fd9-e16c75395757)

**Comment by zhongy-web** [comment]
该怎么拉到类似这种临时版本的依赖呢？
<img width="755" alt="image" src="https://github.com/tx7do/kratos-transport/assets/70579263/e957f459-d09f-44f4-b348-bd879ae96954">
我这里好像只能拉到这个
![image](https://github.com/tx7do/kratos-transport/assets/70579263/d6ec101b-5e6c-4702-92c9-bada2de70eda)

**Comment by tx7do** [comment]
用 go get -u

**Comment by zhongy-web** [comment]
> 用 go get -u

不行，我在你仓库的go.mod里面找了个临时版本号解决了^^
![image](https://github.com/tx7do/kratos-transport/assets/70579263/04e37839-2ff5-4bb3-a675-b653784002db)

**Comment by tx7do** [comment]
呃，不能吧……我好像直接加`-u`就更新到最新的版本了。而且，我还是走的国内的代理。

**Comment by zhongy-web** [comment]
emm，不清楚，我这里go  get -u 只能更新这个你打了tag的https://github.com/tx7do/kratos-transport/的依赖包，但是github.com/tx7do/kratos-transport/transport/rabbitmq 这个还是显示的v1.0.0

**Comment by tx7do** [comment]
哦，你可能要删掉go.mod里面的依赖，然后，再用`go get -u`就可以更新到了。
咳，都怪我，当初年幼无知，给它打了一个tag……
