### ISSUE TITLE
关于子模块go依赖包版本号问题

### ISSUE THREAD

**Issue by code-tbd** [tx7do/kratos-transport#56]
作者你好，我通过`go get github.com/tx7do/kratos-transport/transport/websocket@latest`安装依赖包，版本号是日期哈希值
`github.com/tx7do/kratos-transport/transport/websocket v0.0.0-20230803222306-0904a461c75e`
在日志记录caller时非常长
`INFO ts=2023-08-14T10:28:18+08:00 caller=websocket@v0.0.0-20230803222306-0904a461c75e/server.go:267 service.id=xxx service.name= service.version= trace.id= span.id= msg=[websocket] server listening on: [::]:9002`
能否优化加个tag。
ps：对go包发布不是特别了解，不确定能不能实现子模块的版本管理。

**Comment by tx7do** [comment]
tag太麻烦了，我之前加过一次，还是随机的这个方便——于我而言。

code-tbd ***@***.***> 于2023年8月14日周一 10:33写道：
