### ISSUE TITLE
pulsar 的 keepAlive 有问题？

### ISSUE THREAD

**Issue by moecasts** [tx7do/kratos-transport#59]
请问一下大佬，加了 pulsar server 之后，consul 的 health check 会失败。是这个用法不对吗？
![232171693974888_ pic](https://github.com/tx7do/kratos-transport/assets/37169906/023d30c8-7c92-481f-be8c-4034147b7372)
![232181693974888_ pic](https://github.com/tx7do/kratos-transport/assets/37169906/ff05be3b-d99d-4c0b-ae0a-30876f6b9db6)
![232191693974888_ pic](https://github.com/tx7do/kratos-transport/assets/37169906/fa5bb2eb-899e-4391-a790-df08446d56c8)

**Comment by tx7do** [comment]
默认是不需要打开consul的health check的，因为保活还有另外一套检测机制默认是启动的。

moecasts ***@***.***> 于2023年9月7日周四 10:15写道：

**Comment by moecasts** [comment]
可以单独关 `pulsar` 的 `health check` 吗？这里还有别的服务的。

**Comment by tx7do** [comment]
你是用的consul的注册中心？那么就不需要了，本身就默认开启有一个ttl的保活。kratos的health check貌似有点问题，我没有深入去深究。

**Comment by moecasts** [comment]
好的，感谢～
