### ISSUE TITLE
客户端投递任务示例

### ISSUE THREAD

**Issue by shuqingzai** [tx7do/kratos-transport#6]
客户端如何投递任务呢？大佬出个实践示例可否？

**Comment by tx7do** [comment]
publish topic的话，直接使用Broker就可以了。这个有几个完整的实例，在kratos的examples里面，你可以看看。

**Comment by shuqingzai** [comment]
好的，谢谢

**Comment by shuqingzai** [comment]
你好，刚刚我看了下 [cqrs](https://github.com/go-kratos/examples/tree/main/cqrs) 应该是 [kratos-cqrs](https://github.com/tx7do/kratos-cqrs) 示例中并没有客户端投递的演示，希望可以有 kratos 之间客户端与服务端的示例参考，加深学习，大佬是否可以提供一些示例？

**Comment by tx7do** [comment]
另外还有一个[realtimemap](https://github.com/tx7do/kratos-examples/tree/main/realtimemap)

**Comment by shuqingzai** [comment]
> 另外还有一个[realtimemap](https://github.com/tx7do/kratos-examples/tree/main/realtimemap)

嗯嗯，这个我之前也已经看过，而且最早看过的是: https://developer.aliyun.com/article/881314

**Comment by shuqingzai** [comment]
大致上可以理解，谢谢大佬，只是感觉应该多点示例，方便使用上手

**Comment by tx7do** [comment]
应用级的示例，我倒是觉得还算可以了。

我现在把单元测试也丰富了一下。因为接口是统一的，不同的mq的差异性并不大，使用起来并无太多不同。
