### ISSUE TITLE
rocketmq 订阅不能使用广播模式

### ISSUE THREAD

**Issue by duke123abc** [tx7do/kratos-transport#63]
使用rocketmq 时，无法使用广播模式，是否可以在订阅的时候增加订阅模式选项？

**Comment by tx7do** [comment]
话说，你用的是哪个版本？

**Comment by duke123abc** [comment]
v1.2.2 这个版本

**Comment by tx7do** [comment]
我问的是RocketMQ驱动的版本。我看了一下，只有V2的驱动支持。V5的貌似还没有提供支持，V5的驱动只提供了一个simple的消费者。

**Comment by duke123abc** [comment]
就是v2的
