### ISSUE TITLE
从1.0.12升级到1.1.1 直接失败

### ISSUE THREAD

**Issue by fredmuyu** [tx7do/kratos-transport#68]
go mod tidy
go: finding module for package github.com/tx7do/kratos-transport/_example/api/manual
umcloud-go/app/iot imports
        github.com/tx7do/kratos-transport/transport/mqtt imports
        github.com/tx7do/kratos-transport/broker/mqtt tested by
        github.com/tx7do/kratos-transport/broker/mqtt.test imports
        github.com/tx7do/kratos-transport/_example/api/manual: module github.com/tx7do/kratos-transport@latest found (v1.1.1), but does not contain package github.com/tx7do/kratos-transport/_example/api/manual

**Comment by fredmuyu** [comment]
单独get github.com/tx7do/kratos-transport/broker/mqtt 就可以了，应该是我本地环境问题

**Comment by tx7do** [comment]
跟你环境也没关系，go的cli是这样的，有时候升级不上去，单独get包就可以了。
