### ISSUE TITLE
kafka 订阅通配符主题报错

### ISSUE THREAD

**Issue by fredmuyu** [tx7do/kratos-transport#69]
我订阅主题为：admin*invokereply，结果一直报错，不适用通配符主题就是正常的，不知道是我哪里理解不对吗？

caller=kafka/logger.go:16 trace_id= span_id= msg=Failed to join group local1: [17] Invalid Topic: a request which attempted to access an invalid topic (e.g. one which has an illegal name), or if an attempt was made to write to an internal topic (such as the consumer offsets topic)
caller=kafka/kafka.go:615 trace_id= span_id= msg=[kafka] FetchMessage error: [admin*invokereply][17] Invalid Topic: a request which attempted to access an invalid topic (e.g. one which has an illegal name), or if an attempt was made to write to an internal topic (such as the consumer offsets topic)
caller=kafka/logger.go:16 trace_id= span_id= msg=Failed to sync group local1: [27] Rebalance In Progress: the coordinator has begun rebalancing the group, the client should rejoin the group
caller=kafka/logger.go:16 trace_id= span_id= msg=Failed to sync group local1: [27] Rebalance In Progress: the coordinator has begun rebalancing the group, the client should rejoin the group
caller=kafka/logger.go:16 trace_id= span_id= msg=[17] Invalid Topic: a request which attempted to access an invalid topic (e.g. one which has an illegal name), or if an attempt was made to write to an internal topic (such as the consumer offsets topic)
caller=kafka/logger.go:16 trace_id= span_id= msg=[27] Rebalance In Progress: the coordinator has begun rebalancing the group, the client should rejoin the group
caller=kafka/logger.go:16 trace_id= span_id= msg=[27] Rebalance In Progress: the coordinator has begun rebalancing the group, the client should rejoin the group

**Comment by fredmuyu** [comment]
另外关闭程序的时候会有大量EOF日志，

caller=kafka/server.go:125 trace_id= span_id= kafka=server stopping
caller=kafka/kafka.go:615 trace_id= span_id= msg=[kafka] FetchMessage error: EOF
caller=kafka/kafka.go:615 trace_id= span_id= msg=[kafka] FetchMessage error: EOF
caller=kafka/kafka.go:615 trace_id= span_id= msg=[kafka] FetchMessage error: EOF
caller=kafka/kafka.go:615 trace_id= span_id= msg=[kafka] FetchMessage error: EOF
...

**Comment by tx7do** [comment]
https://github.com/segmentio/kafka-go/issues/283
https://github.com/segmentio/kafka-go/issues/131

官方的Issue显示，他们暂时不支持通配符订阅。
