### ISSUE TITLE
死锁

### ISSUE THREAD

**Issue by cuijianguo** [tx7do/kratos-transport#72]
https://github.com/tx7do/kratos-transport/blob/main/broker/subscriber.go
请问 第35   47行 不会造成死锁吗？

**Comment by fredmuyu** [comment]
我测试的时候也出现了该问题，
在stop mqtt 服务的时候，调用了 Clear，Clear调用了Unsubscribe，结果 mqtt里面的Unsubscribe又调用了Remove，
导致Clear跟Remove里面的sm.Lock()出现了死锁 @tx7do

**Comment by tx7do** [comment]
确实有问题。
