### ISSUE TITLE
异步写 kafka 可否把回调方法也放到 WriterConfig 中？

### ISSUE THREAD

**Issue by dgqypl** [tx7do/kratos-transport#81]
现在默认是异步写，如果写失败了，应用程序没办法感知到错误，无法对错误做后续处理。

相关代码：

默认是异步写：

https://github.com/tx7do/kratos-transport/blob/5abe8d6a8931bd6f3e6298fea446553852b12f36/broker/kafka/kafka.go#L65

创建 Producer：
https://github.com/tx7do/kratos-transport/blob/5abe8d6a8931bd6f3e6298fea446553852b12f36/broker/kafka/writer.go#L112-L128

底层 kafka-go 的回调方法：

https://github.com/segmentio/kafka-go/blob/ebca72eaee918d303c532feb7ff29afdcd8c2efa/writer.go#L161-L182

**Comment by tx7do** [comment]
妥，最近处理下。

Mew151 ***@***.***> 于2024年5月10日周五 17:12写道：
